version: '3'
services:

  my-devel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-devel-app
    environment:
      - PORT=3001
    volumes:
      - ./backend/:/backend
    network_mode: 'host'
    # command: "unbuffer devel /MyApp/script/myapp_server.pl -p $PORT -r -d"
    command: "unbuffer perl /backend/MyApp/script/server.pl --debug --fork --port 3001 --keepalive --restart --restart_delay 1"
